beam: 100
retry_beam: 400

features:
  type: "mfcc"
  use_energy: false
  use_pitch: true
  frame_shift: 10

training:
  - monophone:
      subset: 0
      num_iterations: 200
      max_gaussians: 2000
      boost_silence: 1.25

  - triphone:
      subset: 0
      num_iterations: 200
      num_leaves: 4000
      max_gaussians: 20000
      cluster_threshold: -1
      boost_silence: 1.25
      power: 0.25

  - lda:
      subset: 0
      num_leaves: 5000
      max_gaussians: 30000
      num_iterations: 200
      lda_dimension: 40

  - sat:
      subset: 0
      num_leaves: 8000
      max_gaussians: 80000
      num_iterations: 50
      power: 0.2
      silence_weight: 0.0
      fmllr_update_type: "full"

  - pronunciation_probabilities:
      subset: 0
      silence_probabilities: true

  - sat:
      subset: 0
      num_leaves: 10000
      max_gaussians: 200000
      num_iterations: 50
      power: 0.2
      silence_weight: 0.0
      fmllr_update_type: "full"

  - pronunciation_probabilities:
      subset: 0
      silence_probabilities: true
      optional: true # Skipped if the corpus is smaller than the subset

  - sat:
      subset: 0
      quick: true # Performs fewer fMLLR estimation
      num_iterations: 100
      num_leaves: 15000
      max_gaussians: 300000
      power: 0.2
      silence_weight: 0.0
      fmllr_update_type: "full"
      optional: true # Skipped if the corpus is smaller than the previous subset